import 'dart:io';
import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:path_provider/path_provider.dart';
import 'package:intl/intl.dart';
import '../models/reconstruction_result.dart';
import 'package:image/image.dart' as img;

/// Professional PDF report generation for archaeological findings
class PDFReportService {
  static final PDFReportService _instance = PDFReportService._internal();
  factory PDFReportService() => _instance;
  PDFReportService._internal();

  /// Generate comprehensive archaeological report
  Future<File> generateArchaeologicalReport({
    required String findingName,
    required Map<String, dynamic> findingData,
    required List<File> photoFiles,
    ReconstructionResult? reconstruction,
    List<String>? notes,
  }) async {
    final pdf = pw.Document();
    final dateFormat = DateFormat('MMMM dd, yyyy');
    final timeFormat = DateFormat('HH:mm');

    // Load images
    final photoImages = await _loadPhotos(photoFiles.take(6).toList());

    // Cover Page
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (context) => pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // Header
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(20),
              decoration: pw.BoxDecoration(
                color: PdfColors.teal900,
                borderRadius: pw.BorderRadius.circular(10),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(
                    'ARCHAEOLOGICAL FIELD REPORT',
                    style: pw.TextStyle(
                      color: PdfColors.white,
                      fontSize: 24,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 10),
                  pw.Text(
                    findingName,
                    style: pw.TextStyle(
                      color: PdfColors.amber,
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 30),

            // Metadata Grid
            _buildMetadataSection(findingData, dateFormat, timeFormat),

            pw.Spacer(),

            // Footer
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(15),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.teal200, width: 2),
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.center,
                children: [
                  pw.Text(
                    'Generated by AncientVision',
                    style: pw.TextStyle(
                      fontSize: 12,
                      fontWeight: pw.FontWeight.bold,
                      color: PdfColors.teal900,
                    ),
                  ),
                  pw.SizedBox(height: 5),
                  pw.Text(
                    'Professional Archaeological Management System',
                    style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
                  ),
                  pw.SizedBox(height: 5),
                  pw.Text(
                    dateFormat.format(DateTime.now()),
                    style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );

    // Photo Documentation Page
    if (photoImages.isNotEmpty) {
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildSectionHeader('PHOTOGRAPHIC DOCUMENTATION'),
              pw.SizedBox(height: 20),
              pw.Wrap(
                spacing: 10,
                runSpacing: 10,
                children: photoImages.map((imageData) {
                  return pw.Container(
                    width: 170,
                    height: 170,
                    decoration: pw.BoxDecoration(
                      border: pw.Border.all(color: PdfColors.grey400),
                      borderRadius: pw.BorderRadius.circular(8),
                    ),
                    child: pw.ClipRRect(
                      horizontalRadius: 8,
                      verticalRadius: 8,
                      child: pw.Image(pw.MemoryImage(imageData), fit: pw.BoxFit.cover),
                    ),
                  );
                }).toList(),
              ),
              pw.SizedBox(height: 15),
              pw.Text(
                'Total Photos Captured: ${photoFiles.length}',
                style: pw.TextStyle(fontSize: 11, fontWeight: pw.FontWeight.bold),
              ),
              pw.Text(
                'Photos used for photogrammetry analysis',
                style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700),
              ),
            ],
          ),
        ),
      );
    }

    // 3D Reconstruction Page
    if (reconstruction != null && reconstruction.isComplete) {
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildSectionHeader('3D RECONSTRUCTION ANALYSIS'),
              pw.SizedBox(height: 20),
              _build3DReconstructionInfo(reconstruction),
            ],
          ),
        ),
      );
    }

    // Field Notes Page
    if (notes != null && notes.isNotEmpty) {
      pdf.addPage(
        pw.Page(
          pageFormat: PdfPageFormat.a4,
          build: (context) => pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              _buildSectionHeader('FIELD NOTES'),
              pw.SizedBox(height: 20),
              ...notes.map((note) => pw.Padding(
                    padding: const pw.EdgeInsets.only(bottom: 10),
                    child: pw.Row(
                      crossAxisAlignment: pw.CrossAxisAlignment.start,
                      children: [
                        pw.Container(
                          width: 8,
                          height: 8,
                          margin: const pw.EdgeInsets.only(top: 5, right: 10),
                          decoration: const pw.BoxDecoration(
                            color: PdfColors.teal600,
                            shape: pw.BoxShape.circle,
                          ),
                        ),
                        pw.Expanded(
                          child: pw.Text(
                            note,
                            style: const pw.TextStyle(fontSize: 11),
                          ),
                        ),
                      ],
                    ),
                  )),
            ],
          ),
        ),
      );
    }

    // Save PDF
    final output = await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final file = File('${output.path}/report_${timestamp}.pdf');
    await file.writeAsBytes(await pdf.save());

    return file;
  }

  /// Build metadata section
  pw.Widget _buildMetadataSection(
    Map<String, dynamic> data,
    DateFormat dateFormat,
    DateFormat timeFormat,
  ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'FINDING DETAILS',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.teal900,
            ),
          ),
          pw.SizedBox(height: 15),
          pw.GridView(
            crossAxisCount: 2,
            childAspectRatio: 3,
            crossAxisSpacing: 20,
            mainAxisSpacing: 10,
            children: _buildMetadataFields(data),
          ),
        ],
      ),
    );
  }

  /// Build metadata fields
  List<pw.Widget> _buildMetadataFields(Map<String, dynamic> data) {
    final fields = <pw.Widget>[];

    data.forEach((key, value) {
      if (value != null && value.toString().isNotEmpty) {
        fields.add(
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                _formatFieldName(key),
                style: pw.TextStyle(
                  fontSize: 9,
                  color: PdfColors.grey700,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 3),
              pw.Text(
                value.toString(),
                style: const pw.TextStyle(fontSize: 11),
                maxLines: 2,
                overflow: pw.TextOverflow.clip,
              ),
            ],
          ),
        );
      }
    });

    return fields;
  }

  /// Build 3D reconstruction info
  pw.Widget _build3DReconstructionInfo(ReconstructionResult reconstruction) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(15),
      decoration: pw.BoxDecoration(
        color: PdfColors.teal50,
        borderRadius: pw.BorderRadius.circular(8),
        border: pw.Border.all(color: PdfColors.teal200),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          _buildInfoRow('Reconstruction Method', reconstruction.methodName),
          pw.SizedBox(height: 8),
          _buildInfoRow('Point Count', '${reconstruction.pointCount} points'),
          pw.SizedBox(height: 8),
          _buildInfoRow(
            'Processing Time',
            '${reconstruction.processingTimeSeconds?.toStringAsFixed(1) ?? "N/A"} seconds',
          ),
          pw.SizedBox(height: 8),
          _buildInfoRow('Input Images', '${reconstruction.inputImageCount ?? 0}'),
          pw.SizedBox(height: 8),
          if (reconstruction.qualityMetrics['average_confidence'] != null)
            _buildInfoRow(
              'Average Confidence',
              '${(reconstruction.qualityMetrics['average_confidence'] * 100).toStringAsFixed(0)}%',
            ),
          pw.SizedBox(height: 15),
          pw.Container(
            padding: const pw.EdgeInsets.all(10),
            decoration: pw.BoxDecoration(
              color: PdfColors.amber100,
              borderRadius: pw.BorderRadius.circular(6),
            ),
            child: pw.Row(
              children: [
                pw.Icon(
                  const pw.IconData(0xe86f), // info icon
                  size: 16,
                  color: PdfColors.amber900,
                ),
                pw.SizedBox(width: 10),
                pw.Expanded(
                  child: pw.Text(
                    'This is a sparse preview reconstruction. For production-quality dense models, '
                    'export photos to desktop software (Meshroom, COLMAP).',
                    style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey800),
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  /// Build info row
  pw.Widget _buildInfoRow(String label, String value) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.SizedBox(
          width: 150,
          child: pw.Text(
            '$label:',
            style: pw.TextStyle(
              fontSize: 10,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey800,
            ),
          ),
        ),
        pw.Expanded(
          child: pw.Text(
            value,
            style: const pw.TextStyle(fontSize: 10),
          ),
        ),
      ],
    );
  }

  /// Build section header
  pw.Widget _buildSectionHeader(String title) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(vertical: 10, horizontal: 15),
      decoration: pw.BoxDecoration(
        color: PdfColors.teal100,
        borderRadius: pw.BorderRadius.circular(6),
      ),
      child: pw.Text(
        title,
        style: pw.TextStyle(
          fontSize: 14,
          fontWeight: pw.FontWeight.bold,
          color: PdfColors.teal900,
        ),
      ),
    );
  }

  /// Load and compress photos for PDF
  Future<List<Uint8List>> _loadPhotos(List<File> photoFiles) async {
    final images = <Uint8List>[];

    for (final file in photoFiles) {
      try {
        final bytes = await file.readAsBytes();
        final image = img.decodeImage(bytes);

        if (image != null) {
          // Resize to thumbnail
          final thumbnail = img.copyResize(image, width: 400, height: 400);
          final compressedBytes = Uint8List.fromList(
            img.encodeJpg(thumbnail, quality: 85),
          );
          images.add(compressedBytes);
        }
      } catch (e) {
        print('Error loading photo: $e');
      }
    }

    return images;
  }

  /// Format field name for display
  String _formatFieldName(String key) {
    return key
        .replaceAll('_', ' ')
        .split(' ')
        .map((word) => word[0].toUpperCase() + word.substring(1))
        .join(' ');
  }
}
